name: pdf_tools
description: A Flutter plugin for splitting and merging PDFs
version: 0.1.0
publish_to: "none" # verhindert versehentliches Hochladen auf pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.deinefirma.pdftools
        pluginClass: PdfToolsPlugin
      ios:
        pluginClass: PdfToolsPlugin
      macos:
        pluginClass: PdfToolsPlugin
      windows:
        pluginClass: PdfToolsPlugin

